Portflio mobile menu
MariamOsman11/Portflio pull request #14
Opened 2023-03-14 11:13 UTC by MariamOsman11

# What I did
-Use basic JavaScript syntax.
-Use JavaScript to manipulate DOM elements.

2023-03-14 13:44 UTC, osamaashraf6 reviewed
Hi @MariamOsman11 😊, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🆘💀

- You have submitted a project, that no partner commits at the project, so please 😊 try to make the partner commit to your project to make the project valid as This milestone is a pair-programming activity

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-14 14:03 UTC, franclobo reviewed
Hi @MariamOsman11, 

![roja](https://user-images.githubusercontent.com/58642949/225025738-52da0905-dd94-4634-afd1-0da2622331d9.jpg)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

**You have submitted a project, that is a pair programming activity, there should be commits from your partner. If you don't have a partner in this block please paste a screenshot of your dashboard on the PR.**

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-14 15:12 UTC, MariamOsman11 commented
<img width="1440" alt="Screenshot 2023-03-14 at 18 10 03" src="https://user-images.githubusercontent.com/97727654/225046045-2e6d7478-9f4e-4ad7-aee7-061aa59aa0b6.png">
Dear! Reviewer  i'm working solo this week! kindly see microverse email

2023-03-14 15:48 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @MariamOsman11, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

 - No linter errors .✔️
 - Correct use of GitHub flow. ✔️ 
 - Professional README. ✔️ 

## Aspects to improve ♻️

- [x] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-14 15:48 UTC, leonardodiasb commented on mobile-menu.js
> +closingmenu.addEventListener('click', closemenu);
- [ ] Your mobile menu works, but as the project required and for a better user experience, the menu should also close after the user clicks on any menu link. Kindly implement this feature so if the user scrolls up the menu is closed again and the user does not see the menu open.
 - 
<img width="780" alt="image" src="https://user-images.githubusercontent.com/61919617/225049689-80ff276f-908b-48d7-a491-d2e100ef56eb.png">

2023-03-14 15:48 UTC, leonardodiasb commented on css/mobile-style.css
> +}
- [ ] The menu is a little bit similar to the Figma template, but there are a few differences that make a bad user experience and the menu does not look professional like the color of the menu links, the size and color of the 'X' button and the lack of the 'blur' effect on the section below the menu. Kindly change the size and colors of the menu links, the size, and colors of the 'X' button, and add some 'blur' effect to highlight the menu items and make the mobile menu look more like the Figma template.
 - Your design:
 - 
<img width="433" alt="image" src="https://user-images.githubusercontent.com/61919617/225057495-e3667266-7986-4381-a303-09ff5d715ef5.png">

 - Figma template:
 - 
<img width="205" alt="image" src="https://user-images.githubusercontent.com/61919617/225057634-61657307-7049-4536-9927-5dacacfc2574.png">

2023-03-14 18:31 UTC, Zuhaib042 requested changes
Hi @MariamOsman11 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![close](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)

 ## Highlights
✅ Professional PR
✅ Professional Readme

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-14 18:31 UTC, Zuhaib042 commented on mobile-menu.js
> +  document.body.style.filter = 'blur(0)';
- [ ] When user click on the close button, the `main-header` section remains blurred. instead of giving blur(0) to body, kindly consider giving blur(0) to `main-header` when the user click on close menu button.
your design after closing menu
![as](https://user-images.githubusercontent.com/96683843/225100314-5dd0c1b4-5469-4c82-9d64-44f0f4a5a6a1.jpg)

2023-03-14 18:31 UTC, Zuhaib042 commented on css/mobile-style.css
> +  height: 600px;
- [OPTIONAL] Kindly consider giving this mobile menu `height: 100vh;` in order to contain all the screen when clicking on the mobile menu button to follow figma design and to also follow best user experience.
This requirement was missed by the previous reviewer so I will highly recommend you to apply this.

2023-03-14 18:31 UTC, Zuhaib042 commented on mobile-menu.js
> +function closemenu() {
- [ ] As the previous reviewer mentioned, when the user clicks on any of the mobile-menu options, the mobile menu should disappear but it doesn't disappear on your project so kindly have a look at it and fix it. you can achieve that by selecting all the menu options and then running a forEach method and then addEventListener on them and then you can apply the `visibility: hidden` on `mobile-menu` the same way you are doing on line 10.
   -  When the user clicks (or taps) any option of the mobile menu, the mobile menu disappear.

2023-03-14 18:31 UTC, Zuhaib042 commented on css/mobile-style.css
> +}
- [ ] As the previous previewer mentioned that the menu is a little bit similar to the Figma template, but there are a few differences that make a bad user experience and the menu does not look professional like the color of the menu links, the size and color of the 'X' button. Kindly change the size and colors of the menu links, the size, and colors of the 'X' button, and make the mobile menu look more like the Figma template.
You have applied the blur effect but consider adding a white and big close icon just like in figma design. you can download the icon from [font awesome](https://fontawesome.com/kits/baf7e9f545/use)
Your design:
![re](https://user-images.githubusercontent.com/96683843/225103276-bb5a949c-2564-45e3-bcde-ccbfb0ba31fa.jpg)

figma design
![zx](https://user-images.githubusercontent.com/96683843/225103299-f16ac455-a5a3-4a1c-bd22-3d77835f12d3.jpg)

2023-03-15 09:45 UTC, AbayomiOlaoye requested changes
Hi @MariamOsman11 :wave:, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so_close](https://camo.githubusercontent.com/0c690ab997907a8c79afe7e695c891f6398cdbef93eaf8ce19f652ff321b54f8/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f744b797263304e546c4563475764546870342f67697068792e676966)


 ## Highlights
- Good PR message ✅ 
- Great commit messages ✅ 
- No linter error ✅ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-15 12:24 UTC, IngDavidTM approved these changes
Hi @MariamOsman11 🙋‍♂️, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-15 12:35 UTC, merged